replicaCount: 1

image:
  repository: keerthana2408/eclat
  tag: v3
  pullPolicy: IfNotPresent
  pullSecret: regcred  # <-- secret name created via kubectl

service:
  name: nodejs-service
  port: 80
  targetPort: 3000

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  enabled: true
  className: nginx
  host: localhost
  path: /
  pathType: Prefix